#ifndef DEFINITION_H
#define DEFINITION_H

#include<tuple>

using namespace std;

enum GRID_ACTION_TYPE {
	GRID_ACTION_UP, GRID_ACTION_DOWN, GRID_ACTION_LEFT, GRID_ACTION_RIGHT
};
enum RANDOM_WALK_ACTION_TYPE {
	RANDOM_WALK_ACTION_LEFT, RANDOM_WALK_ACTION_RIGHT
};

typedef pair<int, int> GRID_STATE_TYPE;
typedef int RANDOM_WALK_STATE_TYPE;

typedef tuple<GRID_STATE_TYPE, GRID_ACTION_TYPE, GRID_STATE_TYPE, double> GRID_SASR_QUADRUPLE;
typedef tuple<RANDOM_WALK_STATE_TYPE, RANDOM_WALK_ACTION_TYPE, RANDOM_WALK_STATE_TYPE, double> RANDOM_WALK_SASR_QUADRUPLE;



#endif // !DEFINITION_H

