#ifndef DEFINITION_H
#define DEFINITION_H

#include<tuple>

using namespace std;

enum MAZE_ACTION_TYPE {
	MAZE_ACTION_UP, MAZE_ACTION_DOWN, MAZE_ACTION_LEFT, MAZE_ACTION_RIGHT
};
enum RANDOM_WALK_ACTION_TYPE {
	RANDOM_WALK_ACTION_LEFT, RANDOM_WALK_ACTION_RIGHT
};

typedef pair<int, int> MAZE_STATE_TYPE;
typedef int RANDOM_WALK_STATE_TYPE;

typedef tuple<MAZE_STATE_TYPE, MAZE_ACTION_TYPE, MAZE_STATE_TYPE, double> MAZE_SASR_QUADRUPLE;
typedef tuple<RANDOM_WALK_STATE_TYPE, RANDOM_WALK_ACTION_TYPE, RANDOM_WALK_STATE_TYPE, double> RANDOM_WALK_SASR_QUADRUPLE;



#endif // !DEFINITION_H

